### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by clarkd** [d4v3y0rk/ffpass#10]
Hi,

Just wanted to let you know about a simple Python port of this package I've built. It's pretty much a straight port of this package so wanted to thank you for all your efforts, it was super helpful! 🎉 

https://github.com/clarkd/fordpass-python

I'm planning on integrating it with Home Assistant eventually so can track and automate various things, e.g. notify me (or perhaps automatically lock) if I've left the car unlocked for longer than X minutes, or let me know my windows have been left open etc. 👍 

Cheers,

Dave

**Comment by d4v3y0rk** [comment]
@clarkd This is awesome! I would love to know how you integrate it into homeassistant. I also have a homeassistant setup and would be very interested in that as well.
