### ISSUE TITLE
Getting started help

### ISSUE THREAD

**Issue by swamplynx** [d4v3y0rk/ffpass#7]
Thanks so much for developing this. It would be great if you could enhance the readme to help us n00bs get started running this on AWS Lambda and querying with a Siri shortcut. Thanks!

EDIT: For anyone else looking, I was able to get this running in AWS and can make Siri requests. Took some legwork though, and is probably sloppy, but works for what I need it. I'll try to publish a writeup when I get some time.

**Comment by d4v3y0rk** [comment]
I have actually not set it up that way thb. My current use case is running this inside a telegram bot. If you want to contribute docs for setting it up that way I would suggest forking and updating the readme and opening a PR. I would be happy to merge your guide into the readme. Thanks!

**Comment by swamplynx** [comment]
Good stuff. I have my forked version here for anyone interested in running this in AWS:
https://github.com/swamplynx/ffpass-lambda

Thanks again @d4v3y0rk for developing this. The possibilities really are endless.

**Comment by d4v3y0rk** [comment]
@swamplynx I added a link to your Lambda version in the readme. Love to see this being used. Thanks!
